Milkshakes/urls.py
from django.urls import path
from Milkshakes.views import *
app_name='Milkshakes'
urlpatterns = [
    path('oreoshake/',oreoshake,name='oreoshake'),
    path('kitkatshake/',kitkatshake,name='kitkatshake'),

]

Specific_Url_mapping/urls.py
from django.contrib import admin
from django.urls import path,include
import food, Milkshakes

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('Milkshakes/',include('Milkshakes.urls')),
    
]

food/urls.py
from django.urls import path
from food.views import *
app_name='food'
urlpatterns = [
    path('biriyani/',biriyani,name='biriyani'),
    path('pizza/',pizza,name='pizza'),

]

Milkshakes/models.py
from django.db import models

# Create your models here.

food/models.py
from django.db import models

# Create your models here.

Milkshakes/views.py
from django.shortcuts import render

# Create your views here.
def oreoshake(request):
    return render(request,'oreoshake.html')
def kitkatshake(request):
    return render(request,'kitkatshake.html')
    

food/views.py
from django.shortcuts import render

# Create your views here.
def biriyani(request):
    return render(request,'biriyani.html')
    
def pizza(request):
    return render(request,'pizza.html')

templates/biriyani.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            background-color:lightgrey;
        }
    </style>
</head>
<body>
    <center>
        <h1>Biriyani</h1>
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjgna3FvFrUQo_TAsi7cFJFNc8tsiCoOg28Q&s"/>
        <h1>Select from here</h1>
        <h2><a href="{% url 'food:pizza' %}">GO to Pizza</a></h2>
       <h2>  <a href="{% url 'Milkshakes:oreoshake' %}"> Go to oreoshake</a></h2>
        <h2> <a href="{% url 'Milkshakes:kitkatshake' %}">Go to kitkatshake</a></h2>
    </center>
    
</body>
</html>

templates/kitkatshake.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            background-color:lightsalmon ;
        }
    </style>
</head>
<body>
    <center>
       <h1>Kitkat Shake</h1>
       <img src="https://tastesbetterfromscratch.com/wp-content/uploads/2020/03/Oreo-Milkshake-10.jpg" width="183px" height="275px"/>
       <h1>Select from here</h1>
      <h2>  <a href="{% url 'Milkshakes:oreoshake' %}"> Go to oreoshake</a></h2>
      <h2><a href="{% url 'food:pizza' %}">GO to Pizza</a></h2>
       <h2><a href="{% url 'food:biriyani' %}">Go to Biriyani page</a></h2>

    </center>
</body>
</html>

templates/oreoshake.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            background-color:lightsalmon ;
        }
    </style>
</head>
<body>
    <center>
        
        <h1>OreoShake</h1>
        <img src="https://tastesbetterfromscratch.com/wp-content/uploads/2020/03/Oreo-Milkshake-10.jpg" width="183px" height="275px"/>
        <h1>Select from here</h1>
       <h2> <a href="{% url 'Milkshakes:kitkatshake' %}">Go to kitkatshake</a></h2>
       <h2><a href="{% url 'food:pizza' %}">GO to Pizza</a></h2>
       <h2><a href="{% url 'food:biriyani' %}">Go to Biriyani page</a></h2>

    </center>
</body>
</html>

templates/pizza.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            background-color:lightpink ;
        }
    </style>
</head>
<body>
    <center>
        <h1>Pizza</h1>
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGWky2hHhXnjXCL04j2RiZubMJRsiqUiCOjg&s"/>
        <h1>Select from here</h1>
        <h2><a href="{% url 'food:biriyani' %}">Go to Biriyani page</a></h2>
        <h2>  <a href="{% url 'Milkshakes:oreoshake' %}"> Go to oreoshake</a></h2>
        <h2> <a href="{% url 'Milkshakes:kitkatshake' %}">Go to kitkatshake</a></h2>
    
    </center>
    
</body>
</html>